In [15]:
import pandas as pd

In [16]:
df = pd.read_csv('Karmanta - Dataset.csv')
df

,Employee_ID,Age,Attrition,Business_Travel,Employee_Count,Sub-department,Distance_From_Home,Education,Environment_Satisfaction,Gender,...,Standard_working_hours,Number_of_Companies_Worked_previously,Overtime,Salary_Hike_in_percent,Total_working_years_experience,Work_life_balance,No_of_years_worked_at_current_company,No_of_years_in_current_role,Years_since_last_promotion,Native_Place
0,1,56.0,Yes,Travel Rarely,1,Network Administration,24,Graduation,5,Male,...,80,7,Yes,85,9,1,7,2,4,Hyderabad
1,2,46.0,Yes,Travel Rarely,1,Software Development,45,Degree,5,Male,...,80,3,No,22,18,4,1,2,0,Chennai
2,3,32.0,No,No Travel,1,Data Science,30,Master's,3,Female,...,80,2,Yes,100,O,4,5,5,8,Lucknow
3,4,60.0,Yes,Travel Frequently,1,Data Science,42,Graduation,2,Female,...,80,5,No,72,17,2,1,7,3,Lucknow
4,5,25.0,No,No Travel,1,Network Administration,26,Graduation,4,Female,...,80,9,No,21,12,5,7,2,4,Lucknow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,33.0,Yes,Travel Frequently,1,Data Science,35,Degree,4,Male,...,80,5,No,68,2,2,1,4,4,Hyderabad
9996,9997,62.0,No,Travel Rarely,1,Data Science,30,Degree,5,Female,...,80,3,Yes,55,4,1,0,1,2,Chennai
9997,9998,32.0,No,Travel Rarely,1,Data Science,44,Degree,4,Female,...,80,1,No,87,12,5,8,0,1,Jaipur
9998,9999,18.0,Yes,Travel Rarely,1,Data Science,46,Graduation,2,Male,...,80,9,Yes,79,10,3,8,8,3,Bengaluru
9999,10000,39.0,Yes,No Travel,1,IT Services,1,Degree,1,Female,...,80,2,Yes,34,4,3,2,2,3,Ahmedabad

In [17]:
df.isna().sum()

Employee_ID                              0
Age                                      8
Attrition                                0
Business_Travel                          0
Employee_Count                           0
Sub-department                           0
Distance_From_Home                       0
Education                                0
Environment_Satisfaction                 0
Gender                                   0
Salary                                   0
Over_18                                  0
Job_Involvement                          0
Job_Level                                0
Job_Satisfaction                         0
Marital_Status                           0
Standard_working_hours                   0
Number_of_Companies_Worked_previously    0
Overtime                                 0
Salary_Hike_in_percent                   0
Total_working_years_experience           0
Work_life_balance                        0
No_of_years_worked_at_current_company    0
No_of_years_in_current_role              0
Years_since_last_promotion               0
Native_Place                             0
dtype: int64

In [18]:
df.duplicated().sum()

0

In [19]:
df = df[(df["Age"].notna()) & (df["Age"] != 999)]

In [20]:
df.shape

(9988, 26)

In [21]:
df['Salary'].describe()

count       9988
unique      9709
top       '77630
freq           3
Name: Salary, dtype: object

In [22]:
df['Salary'].dtype

dtype('O')

In [23]:
df['Salary'].unique()

array(['186630', "'78553", "'175003", ..., "'160923", "'163365",
       "'103537"], dtype=object)

In [24]:
df["Salary"].head(20).tolist()

['186630',
 "'78553",
 "'175003",
 "'100795",
 "'75256",
 "'140154",
 "'40476",
 "'188174",
 "'162608",
 "'31890",
 "'93029",
 "'156862",
 "'108342",
 "'47135",
 "'166965",
 "'140423",
 "'91411",
 "'66389",
 "'108525",
 "'140338"]

In [25]:
df["Salary"] = (
    df["Salary"]
    .astype(str)
    .str.replace("'", "", regex=False)
)

df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")

C:\Users\shrey\AppData\Local\Temp\ipykernel_35744\2480042091.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Salary"] = (
C:\Users\shrey\AppData\Local\Temp\ipykernel_35744\2480042091.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")

In [26]:
df['Salary'].dtype

dtype('int64')

In [27]:
df['Salary'].unique()

array([186630,  78553, 175003, ..., 160923, 163365, 103537], dtype=int64)

In [32]:
df['Salary'].describe()

count      9988.000000
mean     114514.475070
std       49020.692168
min       30078.000000
25%       72133.500000
50%      114544.000000
75%      157285.750000
max      199989.000000
Name: Salary, dtype: float64

In [28]:
df['Total_working_years_experience'].head(20).tolist()

['9',
 '18',
 'O',
 '17',
 '12',
 '9',
 '15',
 '9',
 '12',
 '7',
 '16',
 '14',
 '17',
 '15',
 '7',
 'O',
 '9',
 '3',
 '7',
 '17']

In [29]:
df["Total_working_years_experience"] = (
    df["Total_working_years_experience"]
    .astype(str)
    .str.replace("O", "0", regex=False)
)

C:\Users\shrey\AppData\Local\Temp\ipykernel_35744\3577140659.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Total_working_years_experience"] = (

In [30]:
df["Total_working_years_experience"] = (
    df["Total_working_years_experience"]
    .str.replace(r"[^\d]", "", regex=True)
)

C:\Users\shrey\AppData\Local\Temp\ipykernel_35744\655587510.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Total_working_years_experience"] = (

In [31]:
df["Total_working_years_experience"] = pd.to_numeric(
    df["Total_working_years_experience"], errors="coerce"
)

C:\Users\shrey\AppData\Local\Temp\ipykernel_35744\3395120028.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Total_working_years_experience"] = pd.to_numeric(

In [33]:
df['Total_working_years_experience'].dtype

dtype('int64')

In [34]:
df['Total_working_years_experience'].describe()

count    9988.000000
mean        9.977273
std         6.110591
min         0.000000
25%         5.000000
50%        10.000000
75%        15.000000
max        20.000000
Name: Total_working_years_experience, dtype: float64

In [35]:
df['Total_working_years_experience'].unique()

array([ 9, 18,  0, 17, 12, 15,  7, 16, 14,  3, 20,  8, 13,  1,  4, 11,  5,
        2, 10, 19,  6], dtype=int64)

In [36]:
num_cols = df.select_dtypes(include=["int64", "float64"]).columns

df[num_cols].describe()

,Employee_ID,Age,Employee_Count,Distance_From_Home,Environment_Satisfaction,Salary,Job_Involvement,Job_Level,Job_Satisfaction,Standard_working_hours,Number_of_Companies_Worked_previously,Salary_Hike_in_percent,Total_working_years_experience,Work_life_balance,No_of_years_worked_at_current_company,No_of_years_in_current_role,Years_since_last_promotion
count,9988.000000,9988.000000,9988.0,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.0,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000
mean,5002.582899,40.501302,1.0,25.444734,2.988086,114514.475070,2.985983,4.531237,2.990989,80.0,5.010112,50.155487,9.977273,3.003104,4.978674,5.003404,3.986284
std,2885.826791,13.160618,0.0,14.389518,1.414765,49020.692168,1.423319,2.286202,1.427294,0.0,3.166707,29.157273,6.110591,1.412971,3.177636,3.148249,2.587666
min,1.000000,18.000000,1.0,1.000000,1.000000,30078.000000,1.000000,1.000000,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,2504.750000,29.000000,1.0,13.000000,2.000000,72133.500000,2.000000,3.000000,2.000000,80.0,2.000000,25.000000,5.000000,2.000000,2.000000,2.000000,2.000000
50%,5002.500000,40.000000,1.0,25.000000,3.000000,114544.000000,3.000000,5.000000,3.000000,80.0,5.000000,51.000000,10.000000,3.000000,5.000000,5.000000,4.000000
75%,7501.250000,52.000000,1.0,38.000000,4.000000,157285.750000,4.000000,7.000000,4.000000,80.0,8.000000,75.000000,15.000000,4.000000,8.000000,8.000000,6.000000
max,10000.000000,63.000000,1.0,50.000000,5.000000,199989.000000,5.000000,8.000000,5.000000,80.0,10.000000,100.000000,20.000000,5.000000,10.000000,10.000000,8.000000

In [37]:
df[num_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
Employee_ID,9988.0,5002.582899,2885.826791,1.0,2504.75,5002.5,7501.25,10000.0
Age,9988.0,40.501302,13.160618,18.0,29.00,40.0,52.00,63.0
Employee_Count,9988.0,1.000000,0.000000,1.0,1.00,1.0,1.00,1.0
Distance_From_Home,9988.0,25.444734,14.389518,1.0,13.00,25.0,38.00,50.0
Environment_Satisfaction,9988.0,2.988086,1.414765,1.0,2.00,3.0,4.00,5.0
Salary,9988.0,114514.475070,49020.692168,30078.0,72133.50,114544.0,157285.75,199989.0
Job_Involvement,9988.0,2.985983,1.423319,1.0,2.00,3.0,4.00,5.0
Job_Level,9988.0,4.531237,2.286202,1.0,3.00,5.0,7.00,8.0
Job_Satisfaction,9988.0,2.990989,1.427294,1.0,2.00,3.0,4.00,5.0
Standard_working_hours,9988.0,80.000000,0.000000,80.0,80.00,80.0,80.00,80.0
Number_of_Companies_Worked_previously,9988.0,5.010112,3.166707,0.0,2.00,5.0,8.00,10.0
Salary_Hike_in_percent,9988.0,50.155487,29.157273,0.0,25.00,51.0,75.00,100.0
Total_working_years_experience,9988.0,9.977273,6.110591,0.0,5.00,10.0,15.00,20.0
Work_life_balance,9988.0,3.003104,1.412971,1.0,2.00,3.0,4.00,5.0
No_of_years_worked_at_current_company,9988.0,4.978674,3.177636,0.0,2.00,5.0,8.00,10.0
No_of_years_in_current_role,9988.0,5.003404,3.148249,0.0,2.00,5.0,8.00,10.0
Years_since_last_promotion,9988.0,3.986284,2.587666,0.0,2.00,4.0,6.00,8.0

In [38]:
cat_cols = df.select_dtypes(include=["object"]).columns

for col in cat_cols:
    print("\n", col)
    print(df[col].value_counts())

 Attrition
Attrition
No     7743
Yes    2245
Name: count, dtype: int64

 Business_Travel
Business_Travel
Travel Rarely        5980
Travel Frequently    2012
No Travel            1996
Name: count, dtype: int64

 Sub-department
Sub-department
Cyber Security            2078
Software Development      2063
Data Science              1954
IT Services               1954
Network Administration    1939
Name: count, dtype: int64

 Education
Education
Graduation       3063
Degree           2988
Master's         1987
PhD               978
Below College     972
Name: count, dtype: int64

 Gender
Gender
Female    5022
Male      4966
Name: count, dtype: int64

 Over_18
Over_18
Y    9988
Name: count, dtype: int64

 Marital_Status
Marital_Status
Married     3387
Divorced    3350
Single      3251
Name: count, dtype: int64

 Overtime
Overtime
No     6939
Yes    3049
Name: count, dtype: int64

 Native_Place
Native_Place
Jaipur       1048
Delhi        1037
Bengaluru    1027
Mumbai       1020
Ahmedabad    1017
Lucknow      1002
Pune          996
Hyderabad     964
Kolkata       948
Chennai       929
Name: count, dtype: int64

In [39]:
for col in cat_cols:
    print(f"\n==== {col} ====")
    display(df[col].value_counts(dropna=False))
    display((df[col].value_counts(normalize=True) * 100).round(2))

==== Attrition ====

Attrition
No     7743
Yes    2245
Name: count, dtype: int64

Attrition
No     77.52
Yes    22.48
Name: proportion, dtype: float64

==== Business_Travel ====

Business_Travel
Travel Rarely        5980
Travel Frequently    2012
No Travel            1996
Name: count, dtype: int64

Business_Travel
Travel Rarely        59.87
Travel Frequently    20.14
No Travel            19.98
Name: proportion, dtype: float64

==== Sub-department ====

Sub-department
Cyber Security            2078
Software Development      2063
Data Science              1954
IT Services               1954
Network Administration    1939
Name: count, dtype: int64

Sub-department
Cyber Security            20.80
Software Development      20.65
Data Science              19.56
IT Services               19.56
Network Administration    19.41
Name: proportion, dtype: float64

==== Education ====

Education
Graduation       3063
Degree           2988
Master's         1987
PhD               978
Below College     972
Name: count, dtype: int64

Education
Graduation       30.67
Degree           29.92
Master's         19.89
PhD               9.79
Below College     9.73
Name: proportion, dtype: float64

==== Gender ====

Gender
Female    5022
Male      4966
Name: count, dtype: int64

Gender
Female    50.28
Male      49.72
Name: proportion, dtype: float64

==== Over_18 ====

Over_18
Y    9988
Name: count, dtype: int64

Over_18
Y    100.0
Name: proportion, dtype: float64

==== Marital_Status ====

Marital_Status
Married     3387
Divorced    3350
Single      3251
Name: count, dtype: int64

Marital_Status
Married     33.91
Divorced    33.54
Single      32.55
Name: proportion, dtype: float64

==== Overtime ====

Overtime
No     6939
Yes    3049
Name: count, dtype: int64

Overtime
No     69.47
Yes    30.53
Name: proportion, dtype: float64

==== Native_Place ====

Native_Place
Jaipur       1048
Delhi        1037
Bengaluru    1027
Mumbai       1020
Ahmedabad    1017
Lucknow      1002
Pune          996
Hyderabad     964
Kolkata       948
Chennai       929
Name: count, dtype: int64

Native_Place
Jaipur       10.49
Delhi        10.38
Bengaluru    10.28
Mumbai       10.21
Ahmedabad    10.18
Lucknow      10.03
Pune          9.97
Hyderabad     9.65
Kolkata       9.49
Chennai       9.30
Name: proportion, dtype: float64

In [40]:
print("Numeric:", len(num_cols))
print("Categorical:", len(cat_cols))

Numeric: 17
Categorical: 9

In [41]:
df = df.drop(columns=[
    "Employee_Count",
    "Standard_working_hours",
    "Over_18"
])

In [42]:
df

,Employee_ID,Age,Attrition,Business_Travel,Sub-department,Distance_From_Home,Education,Environment_Satisfaction,Gender,Salary,...,Marital_Status,Number_of_Companies_Worked_previously,Overtime,Salary_Hike_in_percent,Total_working_years_experience,Work_life_balance,No_of_years_worked_at_current_company,No_of_years_in_current_role,Years_since_last_promotion,Native_Place
0,1,56.0,Yes,Travel Rarely,Network Administration,24,Graduation,5,Male,186630,...,Married,7,Yes,85,9,1,7,2,4,Hyderabad
1,2,46.0,Yes,Travel Rarely,Software Development,45,Degree,5,Male,78553,...,Divorced,3,No,22,18,4,1,2,0,Chennai
2,3,32.0,No,No Travel,Data Science,30,Master's,3,Female,175003,...,Single,2,Yes,100,0,4,5,5,8,Lucknow
3,4,60.0,Yes,Travel Frequently,Data Science,42,Graduation,2,Female,100795,...,Married,5,No,72,17,2,1,7,3,Lucknow
4,5,25.0,No,No Travel,Network Administration,26,Graduation,4,Female,75256,...,Single,9,No,21,12,5,7,2,4,Lucknow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,33.0,Yes,Travel Frequently,Data Science,35,Degree,4,Male,108566,...,Single,5,No,68,2,2,1,4,4,Hyderabad
9996,9997,62.0,No,Travel Rarely,Data Science,30,Degree,5,Female,115593,...,Married,3,Yes,55,4,1,0,1,2,Chennai
9997,9998,32.0,No,Travel Rarely,Data Science,44,Degree,4,Female,160923,...,Divorced,1,No,87,12,5,8,0,1,Jaipur
9998,9999,18.0,Yes,Travel Rarely,Data Science,46,Graduation,2,Male,163365,...,Married,9,Yes,79,10,3,8,8,3,Bengaluru
9999,10000,39.0,Yes,No Travel,IT Services,1,Degree,1,Female,103537,...,Married,2,Yes,34,4,3,2,2,3,Ahmedabad

In [43]:
(df["No_of_years_worked_at_current_company"] >
 df["Total_working_years_experience"]).sum()

2402

In [44]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Employee_ID,9988.0,5002.582899,2885.826791,1.0,2504.75,5002.5,7501.25,10000.0
Age,9988.0,40.501302,13.160618,18.0,29.00,40.0,52.00,63.0
Distance_From_Home,9988.0,25.444734,14.389518,1.0,13.00,25.0,38.00,50.0
Environment_Satisfaction,9988.0,2.988086,1.414765,1.0,2.00,3.0,4.00,5.0
Salary,9988.0,114514.475070,49020.692168,30078.0,72133.50,114544.0,157285.75,199989.0
Job_Involvement,9988.0,2.985983,1.423319,1.0,2.00,3.0,4.00,5.0
Job_Level,9988.0,4.531237,2.286202,1.0,3.00,5.0,7.00,8.0
Job_Satisfaction,9988.0,2.990989,1.427294,1.0,2.00,3.0,4.00,5.0
Number_of_Companies_Worked_previously,9988.0,5.010112,3.166707,0.0,2.00,5.0,8.00,10.0
Salary_Hike_in_percent,9988.0,50.155487,29.157273,0.0,25.00,51.0,75.00,100.0
Total_working_years_experience,9988.0,9.977273,6.110591,0.0,5.00,10.0,15.00,20.0
Work_life_balance,9988.0,3.003104,1.412971,1.0,2.00,3.0,4.00,5.0
No_of_years_worked_at_current_company,9988.0,4.978674,3.177636,0.0,2.00,5.0,8.00,10.0
No_of_years_in_current_role,9988.0,5.003404,3.148249,0.0,2.00,5.0,8.00,10.0
Years_since_last_promotion,9988.0,3.986284,2.587666,0.0,2.00,4.0,6.00,8.0

In [45]:
df.isna().sum()

Employee_ID                              0
Age                                      0
Attrition                                0
Business_Travel                          0
Sub-department                           0
Distance_From_Home                       0
Education                                0
Environment_Satisfaction                 0
Gender                                   0
Salary                                   0
Job_Involvement                          0
Job_Level                                0
Job_Satisfaction                         0
Marital_Status                           0
Number_of_Companies_Worked_previously    0
Overtime                                 0
Salary_Hike_in_percent                   0
Total_working_years_experience           0
Work_life_balance                        0
No_of_years_worked_at_current_company    0
No_of_years_in_current_role              0
Years_since_last_promotion               0
Native_Place                             0
dtype: int64

In [46]:
df["Business_Travel"].unique()

array(['Travel Rarely', 'No Travel', 'Travel Frequently'], dtype=object)

In [47]:
mask = df["No_of_years_worked_at_current_company"] > df["Total_working_years_experience"]

df.loc[mask, "Total_working_years_experience"] = df.loc[
    mask, "No_of_years_worked_at_current_company"
]

In [48]:
(df["No_of_years_worked_at_current_company"] >
 df["Total_working_years_experience"]).sum()

0

In [49]:
df["External_experience"] = (
    df["Total_working_years_experience"]
    - df["No_of_years_worked_at_current_company"]
)

In [50]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Employee_ID,9988.0,5002.582899,2885.826791,1.0,2504.75,5002.5,7501.25,10000.0
Age,9988.0,40.501302,13.160618,18.0,29.00,40.0,52.00,63.0
Distance_From_Home,9988.0,25.444734,14.389518,1.0,13.00,25.0,38.00,50.0
Environment_Satisfaction,9988.0,2.988086,1.414765,1.0,2.00,3.0,4.00,5.0
Salary,9988.0,114514.475070,49020.692168,30078.0,72133.50,114544.0,157285.75,199989.0
Job_Involvement,9988.0,2.985983,1.423319,1.0,2.00,3.0,4.00,5.0
Job_Level,9988.0,4.531237,2.286202,1.0,3.00,5.0,7.00,8.0
Job_Satisfaction,9988.0,2.990989,1.427294,1.0,2.00,3.0,4.00,5.0
Number_of_Companies_Worked_previously,9988.0,5.010112,3.166707,0.0,2.00,5.0,8.00,10.0
Salary_Hike_in_percent,9988.0,50.155487,29.157273,0.0,25.00,51.0,75.00,100.0
Total_working_years_experience,9988.0,10.933020,5.176046,0.0,7.00,10.0,15.00,20.0
Work_life_balance,9988.0,3.003104,1.412971,1.0,2.00,3.0,4.00,5.0
No_of_years_worked_at_current_company,9988.0,4.978674,3.177636,0.0,2.00,5.0,8.00,10.0
No_of_years_in_current_role,9988.0,5.003404,3.148249,0.0,2.00,5.0,8.00,10.0
Years_since_last_promotion,9988.0,3.986284,2.587666,0.0,2.00,4.0,6.00,8.0
External_experience,9988.0,5.954345,5.577415,0.0,0.00,5.0,10.00,20.0

In [51]:
df.to_csv("karmanta_clean.csv", index=False)